import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Use system fonts / CSS-defined fonts to avoid turbopack internal imports */}
        <meta name="viewport" content="width=device-width,initial-scale=1" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
